// 6. **Empty Declaration:**
//    Declare three variables (`title`, `price`, and `stock`) without assigning values. Later, assign appropriate values to them and print a statement: "The book [title] costs ₹[price] and has [stock] copies available."

// ---
var title;
title = "Kingdom"
let price;
price = 700
let stock;
stock = 300

console.log(`The book ${title} costs ${price} and has ${stock} copies available.`);

