// 1. **String Declaration:**
//    Write code to declare three variables using different quotes:
//    - One with double quotes (`"`), assigning it `"Hello World"`.
//    - One with single quotes (`'`), assigning it `'Welcome to JavaScript'`.
//    - One with backticks (````), assigning it a multi-line string:  
//      ```
//      "JavaScript Strings
//      are Fun!"
//      ```
//    Print all three variables.

// ---

let A = "Hello World";
let B = 'Welcome to JavaScript';
let C = `multi-line string:`;

console.log(A,B,C);